"""Push story opportunities to Notion ideas backlog.

Uses the Notion API to create pages in the existing ideas backlog database.
"""

from __future__ import annotations

import json
import logging
import os

import httpx

from store import get_db, get_unpushed_stories

logger = logging.getLogger(__name__)

NOTION_API = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"
IDEAS_DB_ID = "2e0008aa-e629-8053-a54f-effc74599f10"


def _get_headers() -> dict:
    """Build Notion API headers."""
    token = os.environ.get("NOTION_API_KEY", "")
    if not token:
        raise ValueError("NOTION_API_KEY not set")
    return {
        "Authorization": f"Bearer {token}",
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
    }


def push_story_to_notion(story: dict) -> str | None:
    """Create a Notion page for a story opportunity.

    Returns the Notion page ID if successful, None otherwise.
    """
    headers = _get_headers()

    summary = story.get("summary", "{}")
    if isinstance(summary, str):
        try:
            summary = json.loads(summary)
        except json.JSONDecodeError:
            summary = {}

    headline = story.get("headline", "Untitled Story Idea")
    topic = story.get("topic", "")
    urgency = story.get("urgency", "normal")
    time_estimate = story.get("time_estimate", "")
    contrarian_angle = story.get("contrarian_angle", "")

    data_sources = story.get("data_sources", "[]")
    if isinstance(data_sources, str):
        try:
            data_sources = json.loads(data_sources)
        except json.JSONDecodeError:
            data_sources = []

    # Build the page
    payload = {
        "parent": {"database_id": IDEAS_DB_ID},
        "properties": {
            "Name": {
                "title": [{"text": {"content": headline}}]
            },
        },
        "children": [
            {
                "object": "block",
                "type": "callout",
                "callout": {
                    "icon": {"emoji": "🤖"},
                    "rich_text": [{"text": {"content": "Auto-generated by Pulse"}}],
                },
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {
                    "rich_text": [{"text": {"content": "Story Opportunity"}}],
                },
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [
                        {"text": {"content": f"Topic: {topic}\n"}},
                        {"text": {"content": f"Urgency: {urgency}\n"}},
                        {"text": {"content": f"Time estimate: {time_estimate}\n"}},
                    ],
                },
            },
        ],
    }

    if contrarian_angle:
        payload["children"].append({
            "object": "block",
            "type": "heading_3",
            "heading_3": {
                "rich_text": [{"text": {"content": "Contrarian Angle"}}],
            },
        })
        payload["children"].append({
            "object": "block",
            "type": "paragraph",
            "paragraph": {
                "rich_text": [{"text": {"content": contrarian_angle[:2000]}}],
            },
        })

    if data_sources:
        payload["children"].append({
            "object": "block",
            "type": "heading_3",
            "heading_3": {
                "rich_text": [{"text": {"content": "Data Sources"}}],
            },
        })
        for ds in data_sources[:5]:
            payload["children"].append({
                "object": "block",
                "type": "bulleted_list_item",
                "bulleted_list_item": {
                    "rich_text": [{"text": {"content": str(ds)[:200]}}],
                },
            })

    try:
        resp = httpx.post(
            f"{NOTION_API}/pages",
            headers=headers,
            json=payload,
            timeout=30,
        )
        resp.raise_for_status()
        page_id = resp.json().get("id", "")
        logger.info(f"Created Notion page: {page_id} — {headline[:50]}")
        return page_id

    except Exception as e:
        logger.error(f"Failed to create Notion page for '{headline[:50]}': {e}")
        return None


def push_all_unpushed(db_path=None) -> int:
    """Push all unpushed story opportunities to Notion.

    Returns count of successfully pushed stories.
    """
    conn = get_db(db_path)
    stories = get_unpushed_stories(conn)

    if not stories:
        logger.info("No unpushed story opportunities")
        return 0

    pushed = 0
    for story in stories:
        page_id = push_story_to_notion(story)
        if page_id:
            conn.execute(
                "UPDATE story_opportunities SET pushed_to_notion = 1, notion_page_id = ? WHERE id = ?",
                (page_id, story["id"])
            )
            conn.commit()
            pushed += 1

    logger.info(f"Pushed {pushed}/{len(stories)} stories to Notion")
    return pushed


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    count = push_all_unpushed()
    print(f"Pushed {count} stories to Notion")
