name: Deploy ProMap (Manual)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy geopandas requests

    - name: Download Zillow data
      run: |
        cd PriceMaps
        python scripts/download_data.py

    - name: Generate ProMap
      run: |
        cd PriceMaps
        python scripts/create_sophisticated_map.py

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Deploy to Server via SFTP
      env:
        HOST: ${{ secrets.SFTP_HOST }}
        USER: ${{ secrets.SFTP_USER }}
        KEY: ${{ secrets.SFTP_KEY }}
        REMOTE_BASE: ${{ secrets.REMOTE_BASE }}
      run: |
        cd PriceMaps

        # Set up SSH key
        mkdir -p ~/.ssh
        echo "$KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts 2>/dev/null || true

        # Generate state boundaries (they're needed but not in git)
        python scripts/prepare_state_geometries.py

        # Upload ProMap and all geometry files
        lftp -e "
          set sftp:auto-confirm yes;
          set sftp:connect-program 'ssh -i ~/.ssh/id_rsa';
          set net:max-retries 3;
          set net:timeout 60;
          open -u $USER,dummy sftp://$HOST;
          mkdir -p ${REMOTE_BASE}/live/PriceMaps;
          put output/ProMap.html -o ${REMOTE_BASE}/live/PriceMaps/ProMap.html;
          put output/long_term_changes.json -o ${REMOTE_BASE}/live/PriceMaps/long_term_changes.json;
          put output/state_boundaries_low.json -o ${REMOTE_BASE}/live/PriceMaps/state_boundaries_low.json;
          put output/state_boundaries_medium.json -o ${REMOTE_BASE}/live/PriceMaps/state_boundaries_medium.json;
          put output/state_boundaries_high.json -o ${REMOTE_BASE}/live/PriceMaps/state_boundaries_high.json;
          bye
        " || echo "Upload finished with warnings"

        echo "✅ ProMap and geometry files deployed"
        echo "URL: https://home-economics.us/wp-content/uploads/reports/live/PriceMaps/ProMap.html"
