name: Deploy ProMap (Manual)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy geopandas requests

    - name: Download Zillow data
      run: |
        cd PriceMaps
        python scripts/download_data.py

    - name: Generate ProMap
      run: |
        cd PriceMaps
        python scripts/create_sophisticated_map.py

    - name: Deploy to Server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASS: ${{ secrets.SERVER_PASS }}
        SERVER_PATH: /home2/yxwrmjmy/public_html/wp-content/uploads/reports/live/PriceMaps
      run: |
        cd PriceMaps
        sudo apt-get update && sudo apt-get install -y lftp

        lftp -e "
          set ftp:ssl-allow no;
          open ftp://$SERVER_HOST;
          user $SERVER_USER $SERVER_PASS;
          mkdir -p $SERVER_PATH;
          cd $SERVER_PATH;
          put output/ProMap.html;
          bye
        "

        echo "✅ ProMap deployed to server at $SERVER_PATH"
        echo "URL: https://home-economics.us/wp-content/uploads/reports/live/PriceMaps/ProMap.html"
